<div class="managment_list">

    <h2><?php echo $this->translate($this->list->getTitle()); ?></h2>
    <br />

    <a href="<?php echo $this->url(array('controller'=>$this->list->getControllerName(),'action'=>'add'), 'default');?>" class="btn">
        <i class="icon-plus-sign"></i> <?php echo $this->translate("Add new item"); ?>
    </a>
    <br /><br />

    <?php if ( $this->list->getCount() == 0 ) { ?>
    <div><?php echo $this->translate("The list is empty");?></div>
    <?php } else { ?>
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <?php foreach ($this->list->getTitles() AS $title) { ?>
            <th><?php echo $this->translate($title); ?></th>
            <?php } ?>
        </thead>
        <tbody>
            <?php foreach ($this->list->getList() AS $row) { ?>
            <tr>
                <?php foreach ($row AS $key=>$value) { ?>
                <td><?php
                        if ( substr($key, 0, 1) == "#" )
                        {
                            switch ( substr($key, 1) )
                            {
                                case "url":
                                    {
                                        echo "<a href='" . $this->url(array('controller'=>$value['controller'],'action'=>$value['action']), $value['route']) . "'>";
                                        echo $this->url(array('controller'=>$value['controller'],'action'=>$value['action']), $value['route']);
                                        echo "</a>";
                                    }
                                break;
                                default:
                                    {
                                        if ($value == "")
                                        {
                                            echo "&nbsp;";
                                        }
                                        else
                                        {
                                            echo "<a href='" . $this->url(array('controller'=>$value['controller'],'action'=>$value['action'], 'ID'=>(int)$value['ID']), 'list_' . $value['action']) . "'" . ( $value['action'] == "delete" ? " onclick=\"return confirm('" . $this->translate("Are you sure you want to remove this item?") . "');\"" : "" ) . ">";
                                            echo $this->translate(ucfirst($value['action']));
                                            echo "</a>";
                                        }
                                    }
                                break;
                            }
                        }
                        else
                        {
                            echo $value;
                        }
                ?>
                </td>
                <?php } ?>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <?php } ?>
</div>