<div class="managment_list">
    <h3><?php echo $this->translate($this->list->getTitle()); ?></h3>
    <a href="<?php echo $this->url(array('controller'=>$this->list->getControllerName(),'action'=>'add'), 'default');?>"><?php echo $this->translate("Add new item"); ?></a>
    <?php if ( $this->list->getCount() == 0 ) { ?>
    <div><?php echo $this->translate("The list is empty");?></div>
    <?php } else { ?>
    <table class="list">
        <thead>
            <?php foreach ($this->list->getTitles() AS $title) { ?>
            <th><?php echo $this->translate($title); ?></th>
            <?php } ?>
        </thead>
        <tbody>
            <?php foreach ($this->list->getList() AS $row) { ?>
            <tr>
                <?php foreach ($row AS $key=>$value) { ?>
                <td><?php
                        if ( substr($key, 0, 1) == "#" )
                        {
                            echo "<a href='" . $this->url(array('controller'=>$value['controller'],'action'=>$value['action'], 'ID'=>(int)$value['ID']), 'list_' . $value['action']) . "'" . ( $value['action'] == "delete" ? " onclick=\"return confirm('" . $this->translate("Are you sure you want to remove this item?") . "');\"" : "" ) . ">";
                            echo $this->translate(ucfirst($value['action']));
                            echo "</a>";
                        }
                        else
                        {
                            echo $value;
                        }
                ?>
                </td>
                <?php } ?>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <?php } ?>
</div>