	<h2><?php echo $this->translate('error')?> 404: <?php echo $this->translate('Page not found')?></h2>
	<br />
	<p>
		<b><?php echo $this->translate('Error 404')?></b><br />
		<b><?php echo $this->translate('You can do the following')?></b>
	</p>
	<ul class="list1">		
		<li><a href="<?php echo $this->url(array('controller'=>'contact','action'=>'index'))?>"><?php echo $this->translate('contact with administrator')?></a></li>
		<li><?php echo $this->translate("back to")?> <a href="/"><?php echo $this->translate("main's page")?></a></li>
		<li><?php echo $this->translate("check url")?></li>
	</ul>
<br />
<br />	